### ISSUE TITLE
Package description says "SDL"

### ISSUE THREAD

**Issue by 0xEAB** [ZILtoid1991/bindbc-zstandard#2]
> Dynamic and static bindings to SDL2 and its satellite libraries, compatible with -betterC, `@nogc`, and nothrow.

https://github.com/ZILtoid1991/bindbc-zstandard/blob/v0.1.0-alpha/dub.sdl#L2

**Comment by ZILtoid1991** [comment]
It was an error I didn't caught when I copied from the bindbc-sdl, now it's fixed.

**Comment by 0xEAB** [comment]
Fixed by #1, nice
